# Generated by Django 2.2.13 on 2020-09-29 03:11

import blog.models.article_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='article-default.jpg', upload_to=blog.models.article_models.reference_main_image_path),
        ),
    ]
