# Generated by Django 2.2.16 on 2020-10-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201003_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile-pic-default.jpg', upload_to='profile_pics'),
        ),
    ]
